apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  SPRING_DATA_MONGODB_URI: {{ .Values.env.SPRING_DATA_MONGODB_URI | quote }}
  APP_PORT: {{ .Values.env.APP_PORT | quote }}
  SERVER_PORT: {{ .Values.env.APP_PORT | quote }}

