apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
	selector:
	  matchLabels:
		app: {{ .Release.Name }}
	  template:
	metadata:
	  labels:
		app: {{ .Release.Name }}
	spec:
	  containers:
		- name: app
		  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
		  imagePullPolicy: {{ .Values.image.pullPolicy }}
		  ports:
			- containerPort: {{ .Values.service.port }}
		  envFrom:
			- configMapRef:
				name: {{ .Release.Name }}-config
		  livenessProbe:
			httpGet:
			  path: /actuator/health/liveness
			  port: {{ .Values.service.port }}
			initialDelaySeconds: 40
		  readinessProbe:
			httpGet:
			  path: /actuator/health/readiness
			  port: {{ .Values.service.port }}
			initialDelaySeconds: 40


